# Generated by Django 4.0.3 on 2022-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Type', 'Full Type'), ('Part Type', 'Part Type')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
